MyMessages/urls.py
from django.urls import path
from . import views

app_name = 'messages'
urlpatterns = [
    path('', views.home, name='home'),    
    path('create-user', views.createUser, name='create_user'), 
    path('send-message', views.sendMessage, name='send_message'),
    path('stats', views.stats, name='stats')    
        
]

inara/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyMessages.urls'))
]

MyMessages/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    AGE_BRACKET = [
        ('0-10', '0-10'),
        ('11-20', '11-20'),
        ('21-30', '21-30'),
        ('31-40', '31-40'),
    ]
    username = models.CharField(max_length=100, unique=True)
    age = models.CharField(max_length=100, choices=AGE_BRACKET, default='0-10')
    
    def __str__(self):
        return self.username


class Content(models.Model):
    item = models.CharField(max_length=100)
    
    def __str__(self):
        return self.item 
    
class Message(models.Model):
    receiver = models.ForeignKey(User, related_name='receiver', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    content = models.ForeignKey(Content, related_name='content', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content.item
    

MyMessages/forms.py
from django import forms
from .models import Message, User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'age']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.Select(attrs={'class': 'form-control'}),
        }

        
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['sender', 'receiver', 'content']

MyMessages/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from .models import Message, User, Content
from .forms import UserForm, MessageForm
from django.http import HttpResponse
from django.db.models import Avg

# Create your views here.

def createUser(request):
    if request.method == 'POST':
        print('create post')
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('messages:home')
    else:
        print('create get')
        form = UserForm()
    return render(request, 'messages/create-user.html',{'forms': form})


#  TODO: Add this logic where user cannot send msg to himself
def home(request):
    print('request', request)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('messages:home')
        return render(request, 'messages/home.html', {"forms": form})
    else:
        print('not in if')
    users = User.objects.all()
    content = Content.objects.all()
    messages = Message.objects.all()
    context = {'users': users, 'contents': content, 'messages': messages}
    return render(request, 'messages/home.html', context)

def sendMessage(request):
    print('request', request)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('messages:home')
        return render(request, 'messages/home.html', {"forms": form})
    else:
        print('not in if')
    users = User.objects.all()
    content = Content.objects.all()
    messages = Message.objects.all()
    context = {'users': users, 'contents': content, 'messages': messages}
    return render(request, 'messages/send-message.html', context)


def stats(request):
        users = User.objects.all().values()
        zayyan = users.filter(username='zayyan').values()
        content = Content.objects.all()
        messages = Message.objects.all().values()
        result = User.objects.aggregate(Avg('age'))
        print('result', result)
        # print('zayyan', zayyan)
        # print('users', users[0]['username'])
        # for message in messages:
        #     print('message', message)
        zayyan_id = ''
        users_age = {}
        for user in users:
            age = user['age']
            if(age in users_age):
                users_age[age] += 1
            elif(age not in users_age):
                users_age[age] = +1
            if(user['username'] == 'Zayyan'):
                zayyan_id = user['id']
        # how many texts were sent from you to users of each age bracket
        mySent = []
        receivers = []
        message_frequency = {}
        for message in messages:
            print('messageZ', message['content_id'])
            content = message['content_id']
            if(content in message_frequency):
                message_frequency[str(content)] += 1
            elif(content not in message_frequency):
                message_frequency[str(content)] += 1
            if(message['sender_id'] == zayyan_id):
                mySent.append(message)
                print('checkZ', message['receiver_id'])
                receiver = User.objects.all().filter(id=message['receiver_id'])
                print('receiver', receiver)
                receivers.append(receiver)
                
        print('message_frequency', message_frequency)
        print('mySent', mySent)
        print('receivers', receivers)
        # for userZ in receiver:
        #     print('userZ', userZ)
        print('number of users in each age bracket', users_age)
        context = {'users': users, 'contents': content, 'messages': messages}
        
        
        
        return render(request,'messages/stats.html',{"data":context})

MyMessages/templates/messages/create-user.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My First Bootstrap Page</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <h1> Add User</h1>

    <div class="container mt-5">
    <form method="POST">
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit">Create User</button>
    </form>
    </div>
  

  <!-- Bootstrap JS (Optional) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

MyMessages/templates/messages/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My First Bootstrap Page</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <center>
<div>
 <h1>HOME</h1>
 <br/>
 <br/>
<button color="red"><a href="{% url 'messages:create_user' %}">Add User</a></button>
<button color="red"><a href="{% url 'messages:stats' %}">Show statistics</a></button>
<br/>
<br/>
<!-- <button color="green"><a href="{% url 'messages:send_message' %}">Send Message</a></button> -->


 
</center>

  <!-- Bootstrap JS (Optional) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

MyMessages/templates/messages/send-message.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My First Bootstrap Page</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<center>
    <div>
        Send messages
        <hr>
        <form method="POST">
            {% csrf_token %}
            <select name="sender" id="sender">
                <option selected disabled=true>--Select Sender--</option>
                {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
        tw
          </select>
            <select name="messages" id="messages">
              <option selected disabled=true>--Select message--</option>
              {% for content in contents %}
              <option value="{{ content.id }}">{{ content.item }}</option>
              {% endfor %}
          </select>
          <select name="receiver" id="receiver">
            <option selected disabled=true>--Select Receiver--</option>
            {% for user in users %}
            <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
            <input type="submit" value="send">

            <table border="1">
                <tr>
                    <th>Sender</th>
                    <th>Message</th>
                    <th>Receiver</th>
                </tr>
                {% for result in messages %}
                <tr>
                    <td align="center">{{result.sender}}</td>
                    <td align="center">{{result.content}}</td>
                    <td align="center">{{result.receiver}}</td>
                </tr>
                {% endfor %}
            </table>
<button color="green"><a href="{% url 'messages:home' %}">back</a></button>
            
  
        </center>
  <!-- Bootstrap JS (Optional) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

MyMessages/templates/messages/stats.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My First Bootstrap Page</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<center>
    <h1>Stats</h1>
    <div>
        <h4>No of messages sent from myself to other users</h4>
        <br/>
        <br/>
        <br/>
        <button><a href="{% url 'messages:stats' %}">Hit</a></button>
        <table border="1" >
            <tr>
              <th>Age bracket</th>
              <th>No of messages sent</th>  
            </tr>
            {% for data in datas %}
            <tr>
                <td>{{ data.age }}</td>
                <td>{{ data.count }}</td>
            </tr>
            {%endfor%}
          </table>
    </div>

</center>
  <!-- Bootstrap JS (Optional) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>